import { CompanyIntelligenceProfile, CompanyNotification } from "@/types/companyIntelligence";

// Helper to generate custom mock data for a company to avoid overly verbose static declarations while keeping it fully custom and realistic
function createCompanyProfile(
  id: string,
  name: string,
  logo: string,
  industry: string,
  founded: string,
  employees: string,
  headquarters: string,
  funding: string,
  ceo: string,
  website: string,
  hiringStatus: "Active" | "Paused" | "Selective" | "Accelerated",
  remotePolicy: "Fully Remote" | "Hybrid" | "Office-First" | "Flexible",
  description: string,
  mission: string,
  vision: string,
  products: string[],
  techStack: string[],
  baseSalaryModifier: number // e.g., 1.2 for high-paying, 0.6 for Indian IT services
): CompanyIntelligenceProfile {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  
  // Custom hiring trends
  const hiringTrend = months.map((m, idx) => ({
    month: m,
    count: Math.round((20 + Math.sin(idx) * 10 + (hiringStatus === "Accelerated" ? 25 : hiringStatus === "Paused" ? -15 : 5)) * baseSalaryModifier * 3),
  }));

  const departmentsHiring = [
    { name: "Engineering", count: Math.round(45 * baseSalaryModifier) },
    { name: "Product Management", count: Math.round(12 * baseSalaryModifier) },
    { name: "Design", count: Math.round(8 * baseSalaryModifier) },
    { name: "Marketing", count: Math.round(15 * baseSalaryModifier) },
    { name: "Sales", count: Math.round(22 * baseSalaryModifier) },
  ];

  const recentOpenings = [
    { id: `${id}-op-1`, title: "Senior Software Engineer, Frontend", department: "Engineering", location: headquarters, salaryRange: `$${Math.round(140 * baseSalaryModifier)}k - $${Math.round(190 * baseSalaryModifier)}k` },
    { id: `${id}-op-2`, title: "Product Manager, AI Platform", department: "Product Management", location: headquarters, salaryRange: `$${Math.round(150 * baseSalaryModifier)}k - $${Math.round(210 * baseSalaryModifier)}k` },
    { id: `${id}-op-3`, title: "Full Stack Engineer", department: "Engineering", location: "Remote", salaryRange: `$${Math.round(110 * baseSalaryModifier)}k - $${Math.round(160 * baseSalaryModifier)}k` },
    { id: `${id}-op-4`, title: "UX Designer", department: "Design", location: headquarters, salaryRange: `$${Math.round(95 * baseSalaryModifier)}k - $${Math.round(130 * baseSalaryModifier)}k` },
  ];

  const salaries = [
    { role: "Intern" as const, range: `$${Math.round(35 * baseSalaryModifier)} - $${Math.round(55 * baseSalaryModifier)} / hr`, avg: Math.round(45 * baseSalaryModifier * 2000) },
    { role: "SDE-1" as const, range: `$${Math.round(80 * baseSalaryModifier)}k - $${Math.round(115 * baseSalaryModifier)}k`, avg: Math.round(98 * baseSalaryModifier * 1000) },
    { role: "SDE-2" as const, range: `$${Math.round(110 * baseSalaryModifier)}k - $${Math.round(155 * baseSalaryModifier)}k`, avg: Math.round(132 * baseSalaryModifier * 1000) },
    { role: "Senior" as const, range: `$${Math.round(150 * baseSalaryModifier)}k - $${Math.round(210 * baseSalaryModifier)}k`, avg: Math.round(180 * baseSalaryModifier * 1000) },
    { role: "Lead" as const, range: `$${Math.round(180 * baseSalaryModifier)}k - $${Math.round(250 * baseSalaryModifier)}k`, avg: Math.round(215 * baseSalaryModifier * 1000) },
    { role: "Principal" as const, range: `$${Math.round(230 * baseSalaryModifier)}k - $${Math.round(330 * baseSalaryModifier)}k`, avg: Math.round(280 * baseSalaryModifier * 1000) },
    { role: "Manager" as const, range: `$${Math.round(170 * baseSalaryModifier)}k - $${Math.round(240 * baseSalaryModifier)}k`, avg: Math.round(205 * baseSalaryModifier * 1000) },
  ];

  const countryComparison = [
    { country: "United States", salary: Math.round(175000 * baseSalaryModifier) },
    { country: "United Kingdom", salary: Math.round(115000 * baseSalaryModifier) },
    { country: "Canada", salary: Math.round(125000 * baseSalaryModifier) },
    { country: "Germany", salary: Math.round(102000 * baseSalaryModifier) },
    { country: "India", salary: Math.round(42000 * baseSalaryModifier) },
    { country: "Japan", salary: Math.round(98000 * baseSalaryModifier) },
  ];

  const experienceComparison = [
    { years: "0-2 Years", salary: Math.round(95000 * baseSalaryModifier) },
    { years: "2-5 Years", salary: Math.round(135000 * baseSalaryModifier) },
    { years: "5-8 Years", salary: Math.round(175000 * baseSalaryModifier) },
    { years: "8-12 Years", salary: Math.round(220000 * baseSalaryModifier) },
    { years: "12+ Years", salary: Math.round(290000 * baseSalaryModifier) },
  ];

  const interviewStages = [
    { name: "Online Assessment", description: "Coding and algorithmic questions on hacker rank", duration: "90 Mins" },
    { name: "Technical Round", description: "Deep-dive on problem solving, algorithms, and data structures", duration: "60 Mins" },
    { name: "Machine Coding", description: "Build a working system prototype based on dynamic specifications", duration: "120 Mins" },
    { name: "System Design", description: "Architect scalable backend services or high-performance frontend micro-apps", duration: "60 Mins" },
    { name: "HR", description: "Behavioral assessment & value alignment check", duration: "45 Mins" },
  ];

  const interviewFAQs = [
    { q: "How heavily is system design weighted during the hiring loop?", a: "For mid-to-senior levels, system design is a critical pivot. You are expected to design decoupled systems, justify your architectural choices, and handle scale issues." },
    { q: "What topics are most common in coding rounds?", a: "Trees, Graphs, Dynamic Programming, and LRU Cache structures are highly represented in standard technical interviews." },
    { q: "Is remote work considered a disadvantage in promotion evaluations?", a: "No, performance evaluation metrics are strictly objective and output-focused, ensuring equal career growth." },
  ];

  const prepTips = [
    "Focus on solidifying your understanding of complex data structures and graphs.",
    "Practice design sessions on whiteboard setups like Excalidraw.",
    "Read the engineering blog for case studies on core production issues.",
    "Quantify your resume contributions with specific business and performance numbers."
  ];

  const experienceTimeline = [
    { phase: "Application", duration: "1-5 Days" },
    { phase: "OA screening", duration: "1 Week" },
    { phase: "Technical Rounds", duration: "2 Weeks" },
    { phase: "Onsite Design & Loop", duration: "1 Week" },
    { phase: "Offer Negotiations", duration: "3-5 Days" },
  ];

  const requiredSkills = techStack.slice(0, 5);
  const trendingSkills = techStack.slice(2, 6);

  const learningPriority = [
    { skill: techStack[0], priority: "High" as const, estTime: "2 Weeks" },
    { skill: techStack[1], priority: "High" as const, estTime: "3 Weeks" },
    { skill: techStack[2], priority: "Medium" as const, estTime: "1 Week" },
  ];

  const missingSkills = ["Kubernetes", "GraphQL", "CI/CD Automations"];

  const cultureRatings = {
    workLifeBalance: Math.min(5, Math.max(1, 4.2 + (baseSalaryModifier > 1.3 ? -0.7 : 0.3))),
    benefits: Math.min(5, Math.max(1, 3.8 + baseSalaryModifier * 0.7)),
    growth: Math.min(5, Math.max(1, 3.5 + baseSalaryModifier * 0.8)),
    management: 3.9,
    learning: 4.1,
    remoteCulture: remotePolicy === "Fully Remote" ? 4.8 : remotePolicy === "Hybrid" ? 4.1 : 2.8,
    diversity: 4.3,
  };

  const cultureReviews = [
    { id: `${id}-rev-1`, author: "Staff Software Engineer", title: "Scale is unmatched, but bureaucracy exists", rating: 4, text: "Fabulous perks, high base salaries, and brilliant coworkers. Navigating internal politics can occasionally slow down product delivery, but overall, a world-class workspace." },
    { id: `${id}-rev-2`, author: "Product Designer", title: "Incredible growth opportunity", rating: 5, text: "The cross-functional collaboration is flawless. High accountability culture encourages ownership, and mentoring from industry leaders is incredibly rewarding." },
  ];

  const pros = [
    "Highly competitive cash salaries and stock options",
    "Generous health coverage, parental leaves, and fitness budgets",
    "Opportunities to work on products used by billions daily",
    "Modern high-end laptop configurations and workspace allowances"
  ];

  const cons = [
    "High pressure to perform during biannual stack ranking cycles",
    "Complex organizational structures can feel slow",
    "Strict compliance and security configurations limit toolkit choices"
  ];

  const aiAnalysis = {
    strengths: [`Strong technological moat using ${techStack[0]} and ${techStack[1]}`, "Robust cash positions", "Top-tier engineering talent denseness"],
    weaknesses: ["Antitrust regulatory investigations", "High compensation-related overheads", "Slower project lifecycle turnarounds"],
    growthPrediction: "AI-driven optimizations and core infrastructure expansions will lead to a 15% YoY growth in software engineering hiring.",
    layoffRisk: baseSalaryModifier > 1.25 ? "Moderate" as const : "Low" as const,
    hiringPrediction: hiringStatus === "Accelerated" ? "Aggressive hiring across AI infrastructure and full-stack development." : "Moderate replacement and specific talent acquisitions.",
    careerGrowth: "Excellent brand recognition makes your profile highly sought after post-employment.",
    promotionSpeed: "Standardized promotion levels with clear requirements, taking 1.5 - 3 years per tier.",
    jobStability: "High job stability; low historical restructuring occurrences in core engineering teams.",
    futureOutlook: "Positive, leading the transition to federated AI-powered services.",
    aiSummary: `AI Summary for ${name}: An industry titan characterized by elite talent pools, exceptional compensation structures, and deep investments in ${techStack.join(", ")}. Perfect match for engineers looking for large scale impact and professional credibility.`,
  };

  const covers = [
    "bg-gradient-to-r from-blue-600 to-indigo-800",
    "bg-gradient-to-r from-purple-700 to-violet-900",
    "bg-gradient-to-r from-rose-600 to-pink-800",
    "bg-gradient-to-r from-emerald-600 to-teal-800",
    "bg-gradient-to-r from-amber-500 to-orange-700",
  ];
  
  const coverImage = covers[Math.abs(id.charCodeAt(0) + id.charCodeAt(1)) % covers.length];

  return {
    id,
    name,
    logo,
    coverImage,
    industry,
    founded,
    employees,
    headquarters,
    funding,
    ceo,
    website,
    hiringStatus,
    remotePolicy,
    description,
    mission,
    vision,
    products,
    techStack,
    officeImages: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=600&q=80"
    ],
    hiringTrend,
    hiringVelocity: Math.round(10 + Math.sin(id.charCodeAt(0)) * 12 + (hiringStatus === "Accelerated" ? 15 : 0)),
    departmentsHiring,
    recentOpenings,
    averageHiringTime: hiringStatus === "Accelerated" ? "2.5 Weeks" : "4 Weeks",
    responseRate: Math.round(75 + Math.sin(id.charCodeAt(0)) * 10),
    acceptanceRate: Math.round(65 + Math.cos(id.charCodeAt(0)) * 10),
    hiringPrediction: hiringStatus === "Accelerated" ? "Aggressive growth trend" : "Stable replacement pipeline",
    salaries,
    countryComparison,
    experienceComparison,
    interviewStages,
    interviewDifficulty: baseSalaryModifier > 1.35 ? ("Very Hard" as const) : baseSalaryModifier > 1.1 ? ("Hard" as const) : ("Medium" as const),
    interviewFAQs,
    prepTips,
    experienceTimeline,
    requiredSkills,
    trendingSkills,
    learningPriority,
    missingSkills,
    aiSkillRecommendation: `We recommend focusing on ${techStack[0]}, ${techStack[1]}, and building modular microservices. Focus on profiling performance bottlenecks as it represents a core theme in the company's interviews.`,
    cultureRatings,
    cultureReviews,
    pros,
    cons,
    aiAnalysis,
  };
}

export const mockCompanies: CompanyIntelligenceProfile[] = [
  createCompanyProfile(
    "google",
    "Google",
    "https://logo.clearbit.com/google.com",
    "Technology & AI",
    "1998",
    "182,502",
    "Mountain View, CA",
    "$26M (IPO)",
    "Sundar Pichai",
    "https://google.com",
    "Accelerated",
    "Hybrid",
    "Google organizes the world's information and makes it universally accessible and useful. It is a leader in search, AI, cloud computing, and consumer electronics.",
    "To organize the world's information and make it universally accessible and useful.",
    "To provide access to the world's information in one click.",
    ["Search", "Android", "Google Cloud", "YouTube", "TensorFlow", "Pixel"],
    ["TypeScript", "Go", "Python", "React", "Docker", "Kubernetes"],
    1.45
  ),
  createCompanyProfile(
    "microsoft",
    "Microsoft",
    "https://logo.clearbit.com/microsoft.com",
    "Software & Enterprise",
    "1975",
    "221,000",
    "Redmond, WA",
    "$1B (IPO)",
    "Satya Nadella",
    "https://microsoft.com",
    "Active",
    "Hybrid",
    "Microsoft empowers every person and every organization on the planet to achieve more. Leading developer of Windows, Office, Azure, and GitHub.",
    "Empower every person and every organization on the planet to achieve more.",
    "Empower people through great software any time, any place, and on any device.",
    ["Azure", "Windows", "Office 365", "GitHub", "Xbox", "VS Code"],
    ["C#", "TypeScript", "React", "Azure Boards", "SQL Server", "PowerShell"],
    1.38
  ),
  createCompanyProfile(
    "amazon",
    "Amazon",
    "https://logo.clearbit.com/amazon.com",
    "E-Commerce & Cloud",
    "1994",
    "1,541,000",
    "Seattle, WA",
    "$54M (IPO)",
    "Andy Jassy",
    "https://amazon.com",
    "Selective",
    "Office-First",
    "Amazon is guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking.",
    "To be Earth’s most customer-centric company.",
    "To build a place where people can come to find and discover anything they might want to buy online.",
    ["AWS", "Prime Video", "Retail Store", "Kindle", "Alexa", "Ring"],
    ["Java", "Python", "AWS SDK", "React", "Node.js", "Docker"],
    1.32
  ),
  createCompanyProfile(
    "meta",
    "Meta",
    "https://logo.clearbit.com/meta.com",
    "Social Tech & Metaverse",
    "2004",
    "67,317",
    "Menlo Park, CA",
    "$16B (IPO)",
    "Mark Zuckerberg",
    "https://meta.com",
    "Accelerated",
    "Flexible",
    "Meta builds technologies that help people connect, find communities, and grow businesses. Pioneer in social networking, virtual reality, and open-source AI.",
    "Give people the power to build community and bring the world closer together.",
    "To connect people around the world.",
    ["Facebook", "Instagram", "WhatsApp", "Quest VR", "PyTorch", "Llama AI"],
    ["JavaScript", "React", "PHP", "C++", "Python", "GraphQL"],
    1.48
  ),
  createCompanyProfile(
    "apple",
    "Apple",
    "https://logo.clearbit.com/apple.com",
    "Consumer Tech & Hardware",
    "1976",
    "164,000",
    "Cupertino, CA",
    "$100M (IPO)",
    "Tim Cook",
    "https://apple.com",
    "Selective",
    "Office-First",
    "Apple designs Macs, the best personal computers in the world, along with OS X, iLife, iWork and professional software. Apple leads the digital music revolution.",
    "To bring the best user experience to customers through innovative hardware, software, and services.",
    "To make great products that focus on simplicity and beautiful design.",
    ["iPhone", "MacBook", "iPad", "iOS", "Swift", "Apple Vision Pro"],
    ["Swift", "Objective-C", "C++", "Python", "WebKit", "Metal API"],
    1.42
  ),
  createCompanyProfile(
    "netflix",
    "Netflix",
    "https://logo.clearbit.com/netflix.com",
    "Entertainment & Streaming",
    "1997",
    "13,000",
    "Los Gatos, CA",
    "$82M (IPO)",
    "Ted Sarandos",
    "https://netflix.com",
    "Selective",
    "Flexible",
    "Netflix is the world's leading streaming entertainment service with over 200 million paid memberships in over 190 countries.",
    "To entertain the world.",
    "To be the best global entertainment distribution service.",
    ["Netflix Apps", "Spinnaker", "Chaos Monkey", "Falcon API", "Eureka"],
    ["Java", "JavaScript", "React", "Node.js", "AWS Cloud", "Hadoop"],
    1.50
  ),
  createCompanyProfile(
    "openai",
    "OpenAI",
    "https://logo.clearbit.com/openai.com",
    "Artificial Intelligence",
    "2015",
    "1,200",
    "San Francisco, CA",
    "$13B (Private)",
    "Sam Altman",
    "https://openai.com",
    "Accelerated",
    "Office-First",
    "OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity.",
    "Ensure that artificial general intelligence benefits all of humanity.",
    "AGI that is safe, aligned, and universally accessible.",
    ["ChatGPT", "DALL-E", "OpenAI API", "Sora Video", "GPT-4o"],
    ["Python", "PyTorch", "TypeScript", "Next.js", "Docker", "Kubernetes"],
    1.58
  ),
  createCompanyProfile(
    "nvidia",
    "NVIDIA",
    "https://logo.clearbit.com/nvidia.com",
    "Semiconductors & AI",
    "1993",
    "29,600",
    "Santa Clara, CA",
    "$22M (IPO)",
    "Jensen Huang",
    "https://nvidia.com",
    "Accelerated",
    "Flexible",
    "NVIDIA pioneered accelerated computing to tackle challenges no one else can solve. Our work in AI and graphics is transforming industries.",
    "To solve the world's most difficult computing problems.",
    "To define the future of visual and AI-accelerated computing.",
    ["GeForce GPUs", "CUDA API", "DGX Systems", "Omniverse", "Drive OS"],
    ["C++", "C", "Python", "CUDA", "LLVM", "Linux Systems"],
    1.52
  ),
  createCompanyProfile(
    "oracle",
    "Oracle",
    "https://logo.clearbit.com/oracle.com",
    "Enterprise & Databases",
    "1977",
    "143,000",
    "Austin, TX",
    "$31M (IPO)",
    "Safra Catz",
    "https://oracle.com",
    "Active",
    "Flexible",
    "Oracle provides organizations around the world with silicon-to-consumer enterprise software, cloud infrastructure, and autonomous databases.",
    "Help people see data in new ways, discover insights, unlock endless possibilities.",
    "To be the leading enterprise cloud database provider.",
    ["Oracle DB", "OCI Cloud", "Java SE", "NetSuite", "MySQL"],
    ["Java", "PL/SQL", "C", "Docker", "Kubernetes", "TypeScript"],
    1.15
  ),
  createCompanyProfile(
    "cisco",
    "Cisco",
    "https://logo.clearbit.com/cisco.com",
    "Networking & Security",
    "1984",
    "83,300",
    "San Jose, CA",
    "$224M (IPO)",
    "Chuck Robbins",
    "https://cisco.com",
    "Active",
    "Flexible",
    "Cisco inspires new possibilities by reimagining your applications, securing your data, transforming your infrastructure, and empowering your teams.",
    "Shape the future of the Internet by creating unprecedented value and opportunity.",
    "To change the way we work, live, play, and learn.",
    ["Catalyst Switches", "Webex Teams", "Duo Security", "Meraki Cloud"],
    ["Python", "C++", "Go", "Docker", "Kubernetes", "Linux Networking"],
    1.18
  ),
  createCompanyProfile(
    "adobe",
    "Adobe",
    "https://logo.clearbit.com/adobe.com",
    "Creativity Software",
    "1982",
    "29,000",
    "San Jose, CA",
    "$45M (IPO)",
    "Shantanu Narayen",
    "https://adobe.com",
    "Active",
    "Hybrid",
    "Adobe is the global leader in digital media and digital marketing solutions. Our creative, marketing and document solutions empower everyone.",
    "Changing the world through digital experiences.",
    "To give everyone the tools to tell their stories and create designs.",
    ["Photoshop", "Illustrator", "Creative Cloud", "Acrobat PDF", "Figma Integration"],
    ["C++", "TypeScript", "React", "Rust", "Node.js", "WebAssembly"],
    1.25
  ),
  createCompanyProfile(
    "salesforce",
    "Salesforce",
    "https://logo.clearbit.com/salesforce.com",
    "Cloud Software & CRM",
    "1999",
    "79,000",
    "San Francisco, CA",
    "$110M (IPO)",
    "Marc Benioff",
    "https://salesforce.com",
    "Active",
    "Hybrid",
    "Salesforce is the global leader in Customer Relationship Management (CRM), bringing companies and customers together in the digital age.",
    "Empower companies of every size and industry to connect with their customers in a whole new way.",
    "To democratize enterprise software via the cloud platform.",
    ["Sales Cloud", "Service Cloud", "Slack Platform", "MuleSoft API", "Tableau Analytics"],
    ["Java", "Apex Code", "JavaScript", "TypeScript", "React", "PostgreSQL"],
    1.28
  ),
  createCompanyProfile(
    "ibm",
    "IBM",
    "https://logo.clearbit.com/ibm.com",
    "IT Infrastructure & AI",
    "1911",
    "288,000",
    "Armonk, NY",
    "N/A",
    "Arvind Krishna",
    "https://ibm.com",
    "Selective",
    "Hybrid",
    "IBM integrates technology and services, providing infrastructure, software, and consulting to clients globally in hybrid cloud and enterprise AI.",
    "To lead in the creation, development and manufacture of the industry's most advanced information technologies.",
    "To be the premier partner for enterprise hybrid cloud transformations.",
    ["watsonx AI", "Red Hat Enterprise", "IBM Cloud", "Quantum Computing Systems"],
    ["Python", "Go", "Java", "Docker", "Red Hat OpenShift", "Kubernetes"],
    1.12
  ),
  createCompanyProfile(
    "intel",
    "Intel",
    "https://logo.clearbit.com/intel.com",
    "Semiconductors",
    "1968",
    "124,800",
    "Santa Clara, CA",
    "$6M (IPO)",
    "Pat Gelsinger",
    "https://intel.com",
    "Paused",
    "Hybrid",
    "Intel designs and manufactures the technologies that cloud, smart device, and smart network developers rely on globally.",
    "Create world-changing technology that improves the life of every person on Earth.",
    "To build the dominant silicon foundry and computing platform.",
    ["Core i7 CPUs", "Xeon Scalable", "oneAPI Toolkits", "Intel Foundries"],
    ["C++", "C", "Assembly", "Python", "VHDL/Verilog", "Linux Kernel"],
    1.10
  ),
  // Indian IT Service Providers / Global Integrators
  createCompanyProfile(
    "infosys",
    "Infosys",
    "https://logo.clearbit.com/infosys.com",
    "IT Services & Consulting",
    "1981",
    "328,000",
    "Bengaluru, India",
    "$45M (IPO)",
    "Salil Parekh",
    "https://infosys.com",
    "Active",
    "Hybrid",
    "Infosys is a global leader in next-generation digital services and consulting, helping clients in over 56 countries navigate digital transformations.",
    "To be a globally respected corporation that provides best-of-breed business solutions.",
    "To build a sustainable ecosystem powered by software intelligence.",
    ["EdgeVerve Banking", "Panaya Tools", "Infosys Cobalt", "Topaz AI Platforms"],
    ["Java", "Spring Boot", "Angular", "React", "Oracle DB", "Jenkins CI"],
    0.60
  ),
  createCompanyProfile(
    "tcs",
    "TCS",
    "https://logo.clearbit.com/tcs.com",
    "IT Services & Consulting",
    "1968",
    "601,000",
    "Mumbai, India",
    "$1.2B (IPO)",
    "K. Krithivasan",
    "https://tcs.com",
    "Active",
    "Office-First",
    "Tata Consultancy Services is an IT services, consulting and business solutions organization delivering real results to global businesses.",
    "To help customers achieve their business objectives by providing innovative, best-in-class consulting.",
    "To be recognized as a world-class IT advisor and delivery partner.",
    ["TCS BaNCS", "Ignio Automation", "TCS MasterCraft", "TCS iON Assessments"],
    ["Java", ".NET Core", "React", "Angular", "SQL Server", "Docker"],
    0.62
  ),
  createCompanyProfile(
    "wipro",
    "Wipro",
    "https://logo.clearbit.com/wipro.com",
    "IT Services & Consulting",
    "1945",
    "245,000",
    "Bengaluru, India",
    "N/A",
    "Srinivas Pallia",
    "https://wipro.com",
    "Selective",
    "Hybrid",
    "Wipro is a leading technology services and consulting company focused on building innovative solutions that address clients' digital transformation needs.",
    "To act with integrity, build trust, and deliver top performance for clients.",
    "To empower communities through technology integrations.",
    ["Wipro Holmes AI", "Wipro VirtuaDesk", "Wipro LiVe Light"],
    ["Java", "Spring Boot", "React", "Node.js", "AWS Cloud", "Azure DevOps"],
    0.58
  ),
  createCompanyProfile(
    "accenture",
    "Accenture",
    "https://logo.clearbit.com/accenture.com",
    "Management Consulting & IT",
    "1989",
    "733,000",
    "Dublin, Ireland",
    "$1.6B (IPO)",
    "Julie Sweet",
    "https://accenture.com",
    "Active",
    "Flexible",
    "Accenture is a global professional services company with leading capabilities in digital, cloud, security, and consulting.",
    "To deliver on the promise of technology and human ingenuity.",
    "To help clients create their future and deliver 360-degree business value.",
    ["Accenture Cloud First", "Accenture Song", "myWizard Automation Platform"],
    ["TypeScript", "React", "Java", "Python", "Salesforce Apex", "AWS Cloud"],
    0.80
  ),
  createCompanyProfile(
    "cognizant",
    "Cognizant",
    "https://logo.clearbit.com/cognizant.com",
    "IT Services & Consulting",
    "1994",
    "347,700",
    "Teaneck, NJ",
    "$34M (IPO)",
    "Ravi Kumar S",
    "https://cognizant.com",
    "Active",
    "Hybrid",
    "Cognizant engineers modern businesses, helping clients modernize technology, reimagine processes and transform experiences.",
    "We engineer modern businesses to improve everyday life.",
    "To be the preeminent technology transformation partner globally.",
    ["TriZetto Healthcare Solutions", "Cognizant Neuro AI Platforms"],
    ["Java", "Spring Boot", ".NET Core", "React", "SQL Server", "AWS Cloud"],
    0.72
  ),
  createCompanyProfile(
    "capgemini",
    "Capgemini",
    "https://logo.clearbit.com/capgemini.com",
    "IT Services & Consulting",
    "1967",
    "340,000",
    "Paris, France",
    "N/A",
    "Aiman Ezzat",
    "https://capgemini.com",
    "Active",
    "Hybrid",
    "Capgemini is a global leader in partnering with companies to transform and manage their business by harnessing the power of technology.",
    "Get the future you want.",
    "To guide enterprise clients into a fully digital economy.",
    ["Capgemini Engineering Labs", "Sogeti Services", "Frog Design Studio"],
    ["JavaScript", "Java", "C#", "React", "Azure Boards", "Terraform"],
    0.75
  ),
  createCompanyProfile(
    "hcltech",
    "HCLTech",
    "https://logo.clearbit.com/hcltech.com",
    "IT Services & Software",
    "1976",
    "224,000",
    "Noida, India",
    "N/A",
    "C Vijayakumar",
    "https://hcltech.com",
    "Active",
    "Hybrid",
    "HCLTech is a global technology company home to over 224,000 people across 60 countries, delivering industry-leading software and engineering services.",
    "Supercharging Progress: To help enterprises transform their businesses at speed.",
    "To build a trusted engine of technology invention and scale.",
    ["HCL Software", "HCL DRYiCE Automations", "HCL AppScan Security"],
    ["C#", "Java", "JavaScript", "React", "SQL Server", "Ansible"],
    0.60
  ),
  createCompanyProfile(
    "deloitte",
    "Deloitte",
    "https://logo.clearbit.com/deloitte.com",
    "Professional Services",
    "1845",
    "457,000",
    "London, UK",
    "N/A",
    "Joe Ucuzoglu",
    "https://deloitte.com",
    "Active",
    "Flexible",
    "Deloitte provides audit, consulting, financial advisory, risk management, and tax services to selected clients globally.",
    "To make an impact that matters.",
    "To be the standard of professional excellence globally.",
    ["Deloitte Cortex Analytics", "Deloitte GreenLight Carbon Tracker"],
    ["Python", "JavaScript", "React", "Tableau", "SQL Server", "AWS Cloud"],
    0.82
  ),
];

export const mockNotifications: CompanyNotification[] = [
  {
    id: "cn-1",
    type: "new_hiring",
    companyId: "openai",
    companyName: "OpenAI",
    companyLogo: "https://logo.clearbit.com/openai.com",
    title: "Aggressive AI Hiring Campaign",
    message: "OpenAI launched a fresh search campaign targeting 14 new Senior AI Engineer and Frontend positions.",
    timestamp: "2 Hours Ago",
    isRead: false,
  },
  {
    id: "cn-2",
    type: "referral",
    companyId: "google",
    companyName: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    title: "1st Connection Referral Available",
    message: "Your contact 'Rahul Kumar' is now verified to refer you for general Senior Frontend openings at Google.",
    timestamp: "1 Day Ago",
    isRead: false,
  },
  {
    id: "cn-3",
    type: "salary_updated",
    companyId: "nvidia",
    companyName: "NVIDIA",
    companyLogo: "https://logo.clearbit.com/nvidia.com",
    title: "Salary Benchmark Update",
    message: "Average SDE-2 cash and stock compensation data updated (+8% increase recorded in Silicon Valley).",
    timestamp: "3 Days Ago",
    isRead: true,
  },
  {
    id: "cn-4",
    type: "interview_pattern",
    companyId: "amazon",
    companyName: "Amazon",
    companyLogo: "https://logo.clearbit.com/amazon.com",
    title: "Interview Pattern Change Detected",
    message: "Recent candidate feedback indicates System Design rounds now place 20% more weight on distributed caching.",
    timestamp: "1 Week Ago",
    isRead: true,
  },
  {
    id: "cn-5",
    type: "hiring_again",
    companyId: "intel",
    companyName: "Intel",
    companyLogo: "https://logo.clearbit.com/intel.com",
    title: "Hiring Again for Core Foundry",
    message: "Intel resumed selective hiring for low-level firmware engineers after a brief consolidation phase.",
    timestamp: "2 Weeks Ago",
    isRead: true,
  },
];
