import { useMemo } from "react";
import { useCompanyIntelligenceStore } from "@/store/companyIntelligenceStore";
import { mockCompanies } from "@/services/companyIntelligenceData";
import { Card } from "@/components/ui/card";
import {
  Sparkles, TrendingUp, ShieldAlert, Activity, ArrowUpRight,
  ShieldCheck, Crosshair, Cpu
} from "lucide-react";

export default function AICompanyAnalysis() {
  const { selectedCompanyId } = useCompanyIntelligenceStore();

  const company = useMemo(() => {
    return mockCompanies.find((c) => c.id === selectedCompanyId) || mockCompanies[0];
  }, [selectedCompanyId]);

  const { aiAnalysis } = company;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-extrabold tracking-tight text-foreground">AI Strategic Analysis</h2>
        <p className="text-sm text-muted-foreground mt-1">
          Deep strategic insights, risk assessment, and growth outlooks generated by our proprietary AI models.
        </p>
      </div>

      {/* AI Summary Banner */}
      <Card className="p-6 border-violet-500/30 bg-gradient-to-r from-violet-600/10 via-card to-card backdrop-blur-md relative overflow-hidden">
        <div className="absolute top-0 right-0 p-6 opacity-10">
          <Sparkles className="h-24 w-24 text-violet-500" />
        </div>
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="h-5 w-5 text-violet-500" />
            <h3 className="text-sm font-bold text-foreground">AI Executive Summary</h3>
          </div>
          <p className="text-sm md:text-base text-foreground/90 font-medium leading-relaxed max-w-4xl">
            "{aiAnalysis.aiSummary}"
          </p>
        </div>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* SWOT - Strengths */}
        <Card className="p-6 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-5">
            <ShieldCheck className="h-5 w-5 text-emerald-500" />
            <h3 className="text-sm font-bold text-foreground">Strategic Strengths (Moats)</h3>
          </div>
          <ul className="space-y-4">
            {aiAnalysis.strengths.map((item, idx) => (
              <li key={idx} className="flex items-start gap-3">
                <div className="h-5 w-5 rounded-full bg-emerald-500/10 flex items-center justify-center shrink-0 border border-emerald-500/20">
                  <span className="text-[10px] font-extrabold text-emerald-500">{idx + 1}</span>
                </div>
                <span className="text-sm text-foreground/80 leading-relaxed font-medium mt-0.5">{item}</span>
              </li>
            ))}
          </ul>
        </Card>

        {/* SWOT - Weaknesses */}
        <Card className="p-6 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-5">
            <Crosshair className="h-5 w-5 text-rose-500" />
            <h3 className="text-sm font-bold text-foreground">Strategic Vulnerabilities</h3>
          </div>
          <ul className="space-y-4">
            {aiAnalysis.weaknesses.map((item, idx) => (
              <li key={idx} className="flex items-start gap-3">
                <div className="h-5 w-5 rounded-full bg-rose-500/10 flex items-center justify-center shrink-0 border border-rose-500/20">
                  <span className="text-[10px] font-extrabold text-rose-500">{idx + 1}</span>
                </div>
                <span className="text-sm text-foreground/80 leading-relaxed font-medium mt-0.5">{item}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Risk & Growth Metrics */}
        <Card className="p-5 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 text-muted-foreground mb-3">
            <ShieldAlert className="h-4 w-4 text-amber-500" />
            <span className="text-[10px] font-bold uppercase tracking-wider">Layoff Risk</span>
          </div>
          <h4 className={`text-lg font-black ${
            aiAnalysis.layoffRisk === "High" ? "text-rose-500" :
            aiAnalysis.layoffRisk === "Moderate" ? "text-amber-500" :
            "text-emerald-500"
          }`}>
            {aiAnalysis.layoffRisk}
          </h4>
        </Card>

        <Card className="p-5 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 text-muted-foreground mb-3">
            <TrendingUp className="h-4 w-4 text-blue-500" />
            <span className="text-[10px] font-bold uppercase tracking-wider">Promotion Speed</span>
          </div>
          <h4 className="text-sm font-bold text-foreground leading-snug">
            {aiAnalysis.promotionSpeed}
          </h4>
        </Card>

        <Card className="p-5 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 text-muted-foreground mb-3">
            <Activity className="h-4 w-4 text-indigo-500" />
            <span className="text-[10px] font-bold uppercase tracking-wider">Job Stability</span>
          </div>
          <h4 className="text-sm font-bold text-foreground leading-snug">
            {aiAnalysis.jobStability}
          </h4>
        </Card>

        <Card className="p-5 border-border bg-card/60 backdrop-blur-sm">
          <div className="flex items-center gap-2 text-muted-foreground mb-3">
            <ArrowUpRight className="h-4 w-4 text-fuchsia-500" />
            <span className="text-[10px] font-bold uppercase tracking-wider">Career Growth</span>
          </div>
          <h4 className="text-sm font-bold text-foreground leading-snug">
            {aiAnalysis.careerGrowth}
          </h4>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-6 border-border bg-muted/20">
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-bold text-foreground">Hiring Prediction Model</h3>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            {aiAnalysis.hiringPrediction}
          </p>
        </Card>
        
        <Card className="p-6 border-border bg-muted/20">
          <div className="flex items-center gap-2 mb-3">
            <Cpu className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-bold text-foreground">12-Month Future Outlook</h3>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            {aiAnalysis.futureOutlook}
          </p>
        </Card>
      </div>
    </div>
  );
}
