package com.jobpilotai.backend.orchestrator.executor;

import com.jobpilotai.backend.application.domain.Application;
import com.jobpilotai.backend.application.service.ApplicationService;
import com.jobpilotai.backend.browserautomation.domain.AutomationExecution;
import com.jobpilotai.backend.browserautomation.engine.AutomationEngine;
import com.jobpilotai.backend.candidateprofile.domain.CandidateProfile;
import com.jobpilotai.backend.candidateprofile.service.CandidateProfileBuilderService;
import com.jobpilotai.backend.job.collector.JobCollectionService;
import com.jobpilotai.backend.job.service.JobMatchingService;
import com.jobpilotai.backend.orchestrator.domain.OrchestratorWorkflow;
import com.jobpilotai.backend.orchestrator.domain.WorkflowStepName;
import com.jobpilotai.backend.orchestrator.pipeline.PipelineExecutor;
import com.jobpilotai.backend.resume.service.ResumeTailoringService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Executes individual workflow steps by delegating to the appropriate service.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class WorkflowExecutor {

    private final PipelineExecutor pipelineExecutor;
    
    private final CandidateProfileBuilderService profileService;
    private final JobCollectionService jobCollectionService;
    private final JobMatchingService matchingService;
    private final ResumeTailoringService tailoringService;
    private final ApplicationService applicationService;
    private final AutomationEngine automationEngine;

    public void executeStep(OrchestratorWorkflow workflow, String stepName) {
        log.info("Executing logic for step: {} in workflow: {}", stepName, workflow.getPublicId());
        
        try {
            if (WorkflowStepName.RESUME_UPLOAD.name().equals(stepName)) {
                log.info("Resume Upload already completed.");
            } else if (WorkflowStepName.RESUME_PARSING.name().equals(stepName)) {
                log.info("Resume Parsing handled by pipeline service.");
            } else if (WorkflowStepName.CANDIDATE_PROFILE_GENERATION.name().equals(stepName)) {
                log.info("Candidate Profile generated by pipeline service.");
            } else if (WorkflowStepName.JOB_COLLECTION.name().equals(stepName)) {
                jobCollectionService.collectFromAllSources();
            } else if (WorkflowStepName.JOB_MATCHING.name().equals(stepName)) {
                log.info("Job Matching handled by pipeline service loop.");
            } else if (WorkflowStepName.RESUME_TAILORING.name().equals(stepName)) {
                log.info("Resume Tailoring handled by pipeline service loop.");
            } else if (WorkflowStepName.COVER_LETTER_GENERATION.name().equals(stepName)) {
                log.info("Cover Letter Generation handled by pipeline service loop.");
            } else if (WorkflowStepName.APPLICATION_QUEUE.name().equals(stepName)) {
                log.info("Application Queueing handled by pipeline service loop.");
            } else if (WorkflowStepName.BROWSER_AUTOMATION.name().equals(stepName)) {
                // If it's a generic step, we wait. The pipeline service orchestrates the loop.
                log.info("Browser Automation executed per application in pipeline service loop.");
            } else if (WorkflowStepName.APPLICATION_TRACKING.name().equals(stepName)) {
                log.info("Tracking updated in pipeline loop.");
            } else if (WorkflowStepName.NOTIFICATION.name().equals(stepName)) {
                log.info("Execution complete notification.");
            } else {
                throw new IllegalArgumentException("Unknown step: " + stepName);
            }

            pipelineExecutor.completeStep(workflow, stepName, "success");

        } catch (Exception e) {
            log.error("Error executing step: {}", stepName, e);
            pipelineExecutor.failStep(workflow, stepName, e.getMessage());
        }
    }
}
