spring:
  application:
    name: jobpilot-ai-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jobpilot:
  application:
    version: 0.0.1-SNAPSHOT

logging:
  level:
    root: INFO
    com.jobpilotai.backend: INFO
